window.VERB_DATA = [
  { rank: 1, word: "sein", meaning: "to be, his, its, to have (as auxiliary), being, existence" },
  { rank: 2, word: "haben", meaning: "to have, to possess, to have (auxiliary), to have to, must, to be, to feel" },
  { rank: 3, word: "werden", meaning: "to become, to get, to turn, will, shall (auxiliary), to be (auxiliary for passive), to grow, becoming, development, growth, genesis" },
  { rank: 4, word: "können", meaning: "can, to be able to, may, might, to be possible, be allowed to" },
  { rank: 5, word: "müssen", meaning: "must, have to, need to, must be, has to be, must have, ought to, should" },
  { rank: 6, word: "sagen", meaning: "say, tell, speak, utter, report, narrate, recount, relate, state, declare, assert, order, instruct, express, opine, mention, indicate" },
  { rank: 7, word: "machen", meaning: "do, make, perform, carry out, create, build, cause, provoke, earn, gain, obtain, participate, take part, join, prepare, arrange, produce, emit" },
  { rank: 8, word: "geben", meaning: "give, hand, provide, deliver, cause, produce, yield, result in, there is, there are, exist, be present, allow, enable, grant, announce, declare, state" },
  { rank: 9, word: "kommen", meaning: "to come, to arrive, to happen, to occur, to come about, to become, to reach, to attain, to come from, to be from, to come to mind, to get an idea, to think of, to come to, to arrive at" },
  { rank: 10, word: "sollen", meaning: "should, must, have to, ought to, is supposed to, is expected to, should not, are not to, is said to, reportedly" },
  { rank: 11, word: "wollen", meaning: "to want, to intend, to wish, to plan, to really want, to be determined to, to insist on, to want to ask, to wish to ask, to request politely, to be necessary, to have to be done, to need to be done" },
  { rank: 12, word: "gehen", meaning: "walk, go, work, function, operate, leave, depart, progress, advance, proceed, to be (doing), to feel, to be about, to concern, to deal with, to be possible, to be allowed, to work (function)" },
  { rank: 13, word: "wissen", meaning: "to know" },
  { rank: 14, word: "sehen", meaning: "see, perceive, understand, comprehend, grasp, meet, visit, check, verify, make sure, look, watch, glance" },
  { rank: 15, word: "lassen", meaning: "to let, to allow, to permit, to leave, to abandon, to have (something done), to get (something done), stop, quit, cease, leave off, let, leave, allow, omit, leave out, skip, not do" },
  { rank: 16, word: "stehen", meaning: "to stand, to be, to be located, to be written, to be stated, to say, to stand by, to uphold, to stick to, to be unemployed, to be out of work, to suit, to look good on, to become" },
  { rank: 17, word: "finden", meaning: "find, discover, think, consider, reach, get to, locate, come across" },
  { rank: 18, word: "bleiben", meaning: "to stay, to remain, to keep, to wait, remain, be left over, stay, continue to be" },
  { rank: 19, word: "liegen", meaning: "lie, be lying, be located, be situated, be due to, be caused by, be attributable to, be in, be in a state of" },
  { rank: 20, word: "heißen", meaning: "to be called, to mean, to command, to order, to bid, to imply, to signify" },
  { rank: 21, word: "denken", meaning: "to think, to consider, to have in mind, to believe, to opine, to plan, to intend, to remember, to think of, to bear in mind, to judge, to evaluate, to assess" },
  { rank: 22, word: "nehmen", meaning: "take, grasp, pick up, get, accept, receive, take (transport), make (a decision), take (an action), take (medication), adopt, assume, take (a stance)" },
  { rank: 23, word: "tun", meaning: "to do, to make, to perform, to act, to put, to place, to set, to cause, to effect, to pretend, to act as if, to feign" },
  { rank: 24, word: "dürfen", meaning: "be allowed, be permitted, may, might, could, possibly, should, can, feel free to, must not, not allowed, forbidden" },
  { rank: 25, word: "glauben", meaning: "to believe in, to trust, to think, to suppose, to guess, to believe, to accept as true, to be of the opinion" },
  { rank: 26, word: "halten", meaning: "hold, keep, maintain, stop, halt, consider, regard, deem, fulfill, adhere to, respect, organize, conduct, host, think of, have an opinion about, hold (an opinion), care for, last, endure, store, save, preserve" },
  { rank: 27, word: "nennen", meaning: "to name, to call, to mention, to refer to, to cite, to label, to classify, to categorize, to state, to provide, to give, to tell" },
  { rank: 28, word: "mögen", meaning: "to like, to be fond of, to prefer, may, might, could (as in 'it may be'), to care for, to be willing to, to be inclined to, to feel like, to choose, to rather" },
  { rank: 29, word: "zeigen", meaning: "to show, to display, to present, to point, to indicate, show, demonstrate, evidence, prove, indicate, appear, manifest, emerge, reveal itself, report, declare, denounce, notify" },
  { rank: 30, word: "führen", meaning: "lead, guide, direct, lead to, go to, take to, conduct, keep, maintain, hold, head, manage, be in charge of, result in, cause" },
  { rank: 31, word: "sprechen", meaning: "talk, speak, converse, pronounce, articulate, address, speak to, give a speech, talk on the phone, speak on the phone, speak (a language)" },
  { rank: 32, word: "bringen", meaning: "to bring, to take, to carry, to cause, to lead to, to bring about, to bring (as a gift), to give, to achieve, to yield, to bring (results), to publish, to broadcast, to report" },
  { rank: 33, word: "leben", meaning: "to live, to be alive, life, existence, to reside, to dwell" },
  { rank: 34, word: "fahren", meaning: "to drive, to travel, to go by, to take, to operate, to handle, to sail, to go by boat, to move quickly, to dash" },
  { rank: 35, word: "meinen", meaning: "to mean, to think, to believe, to opine, to refer to, to allude to, to intend, to have in mind" },
  { rank: 36, word: "fragen", meaning: "to ask, to inquire, to wonder, to be interested, to ask about, to ask for, to request, to solicit" },
  { rank: 37, word: "kennen", meaning: "to know, to be familiar with, to recognize, to identify, to be aware of, to be acquainted with" },
  { rank: 38, word: "gelten", meaning: "to be valid, to apply, to be in effect, to count, to be considered, to be recognized, to pass for, to be for, to be intended for, to be directed at" },
  { rank: 39, word: "stellen", meaning: "to put, to place, to set, to ask, to pose, to raise, to provide, to make available, to supply, to adjust, to regulate, surrender, turn oneself in, present oneself, feign, simulate, pretend, fake" },
  { rank: 40, word: "spielen", meaning: "to play, to game, to engage in a game, to act, to perform, to play a role, to star, play, perform, gamble, act, pretend" },
  { rank: 41, word: "arbeiten", meaning: "to work, to labor, to be employed, to function, to operate, work on, study, dedicate oneself to, collaborate, work together, cooperate" },
  { rank: 42, word: "brauchen", meaning: "to need, to require, not to need to, not to have to, to spend, to use up, to consume" },
  { rank: 43, word: "folgen", meaning: "to follow, to trail, to obey, to comply with, to result, to ensue, to follow from" },
  { rank: 44, word: "lernen", meaning: "to learn, to study, to memorize, to learn by heart, to find out, to discover" },
  { rank: 45, word: "bestehen", meaning: "to exist, to be, to persist, to continue, to pass, to succeed, to overcome, to insist, to demand, to stand firm, to consist of, to be composed of, to be made up of" },
  { rank: 46, word: "verstehen", meaning: "to understand, to comprehend, to grasp, to get along, to understand each other, to have a good relationship, to perceive, to realize" },
  { rank: 47, word: "setzen", meaning: "to put, to place, to set, to sit, to seat oneself, to make sit, to establish, to fix, to define, to bet, to wager, to stake, to start, to initiate, to set in motion, to implement, to apply, to use, to employ" },
  { rank: 48, word: "bekommen", meaning: "get, receive, obtain, catch, contract, develop, acquire" },
  { rank: 49, word: "beginnen", meaning: "start, begin, commence, initiate, take up, open" },
  { rank: 50, word: "erzählen", meaning: "tell, narrate, recount, relate, inform, communicate, report, explain, clarify" },
  { rank: 51, word: "versuchen", meaning: "try, attempt, endeavor, taste, sample, try to persuade, try to convince, tempt" },
  { rank: 52, word: "schreiben", meaning: "write, pen, author, compose, text, message, write (a message), write down, note down, record, jot down, stipulate, document, formalize, set down in writing" },
  { rank: 53, word: "laufen", meaning: "run, jog, walk, go on foot, stroll, operate, function, work, go, proceed, develop, happen, be shown, be screened, be broadcast, play, flow, leak, drain" },
  { rank: 54, word: "erklären", meaning: "explain, clarify, declare, state, announce, account for, interpret" },
  { rank: 55, word: "entsprechen", meaning: "correspond, match, agree, conform, comply, meet, fulfill, satisfy, comply with, be equivalent to, correspond to, be proportional to" },
  { rank: 56, word: "sitzen", meaning: "to sit, to be seated, to be located, to be situated, to fit, to be on, to be a member of, to serve on, to be stuck, to be trapped, to be caught" },
  { rank: 57, word: "ziehen", meaning: "pull, drag, draw, move, relocate, take out, extract, pull out, draw out, trace, attract, stretch, lengthen, inhale, puff, draw (on a cigarette), derive, conclude, infer, draw (a conclusion), move (a piece), play (a piece)" },
  { rank: 58, word: "scheinen", meaning: "seem, appear, look, shine, gleam, radiate, look likely" },
  { rank: 59, word: "fallen", meaning: "fall, drop, descend, perish, die, be defeated, decrease, decline, diminish, fall on, occur on, happen on, be felled, be cut down, be knocked down, be brought down, be demolished" },
  { rank: 60, word: "gehören", meaning: "to belong to, to be owned by, to be part of, to be included in, to be appropriate, to be suitable, to be proper, to be counted among" },
  { rank: 61, word: "entstehen", meaning: "arise, originate, emerge, come into being, be created, form, develop, result, be produced, occur, come about" },
  { rank: 62, word: "erhalten", meaning: "receive, get, obtain, preserve, maintain, conserve, keep, sustain, support, uphold" },
  { rank: 63, word: "treffen", meaning: "meet, encounter, get together, hit, strike, reach, affect, impact, make, take, come to" },
  { rank: 64, word: "suchen", meaning: "to search for, to look for, to seek, to seek information, to investigate, to pick up, to fetch, to collect, to strive for, to recruit" },
  { rank: 65, word: "legen", meaning: "to lay, to put, to place, to invest, to put in, to spend, to set, to establish, to fix, to determine, bet, wager, stake, place a bet, lay eggs, deposit eggs" },
  { rank: 66, word: "vorstellen", meaning: "to introduce, to present, imagine, visualize, conceive, place in front, put in front, set in front" },
  { rank: 67, word: "handeln", meaning: "to act, to take action, to operate, to negotiate, to bargain, to deal, to trade, to deal in, to sell, to be about, to deal with, to concern" },
  { rank: 68, word: "erreichen", meaning: "achieve, reach, attain, accomplish, arrive at, get to, contact, get hold of, be available, extend to, attain (a level)" },
  { rank: 69, word: "tragen", meaning: "carry, bear, transport, wear, dress in, take on, assume, bear (fruit), yield, produce, contribute, bring, add" },
  { rank: 70, word: "schaffen", meaning: "achieve, manage, succeed, accomplish, create, produce, make, generate, work, be employed, be busy, transport, move, carry" },
  { rank: 71, word: "lesen", meaning: "read (verb), read (interpret), decipher, study (at university), read (a subject), read (aloud), give a reading" },
  { rank: 72, word: "verlieren", meaning: "lose, misplace, be defeated, forfeit, get lost, disappear" },
  { rank: 73, word: "darstellen", meaning: "represent, describe, depict, portray, act, play, perform, constitute, signify, amount to, show, exhibit, display, explain, clarify, present, illustrate" },
  { rank: 74, word: "erkennen", meaning: "recognize, identify, perceive, discern, admit, acknowledge, accept, realize, understand, comprehend, grasp" },
  { rank: 75, word: "entwickeln", meaning: "develop, evolve, create, produce, process, unfold, unroll, deploy" },
  { rank: 76, word: "reden", meaning: "to speak, to talk, to converse, to give a speech, to deliver a talk, to address, to persuade, to convince, to talk into" },
  { rank: 77, word: "aussehen", meaning: "look, appear, seem, look for, search for" },
  { rank: 78, word: "erscheinen", meaning: "appear, emerge, show up, become visible, be published, be released, come out, seem, look" },
  { rank: 79, word: "bilden", meaning: "form, create, build, make, shape, educate, train, instruct, teach, constitute, compose, make up" },
  { rank: 80, word: "anfangen", meaning: "to start, to begin, to commence, to take up, to initiate, to get started" },
  { rank: 81, word: "erwarten", meaning: "expect, await, demand, wait for, have an appointment with" },
  { rank: 82, word: "wohnen", meaning: "to live, to reside, to dwell, live, reside, stay, lodge, attend, be present at" },
  { rank: 83, word: "betreffen", meaning: "to affect, to concern, to involve, to relate to, to refer to, to be about, to deal with" },
  { rank: 84, word: "warten", meaning: "to wait, wait, to pause, to halt, to look forward to, to await eagerly, maintain, service, upkeep" },
  { rank: 85, word: "vergehen", meaning: "to pass, to elapse, to go by, to disappear, to vanish, to fade away, to commit an offense, to transgress, to err" },
  { rank: 86, word: "helfen", meaning: "to help, to assist, to aid, to contribute, to support, to relieve, to ease, to improve, to be useful, to be beneficial" },
  { rank: 87, word: "gewinnen", meaning: "to win, to be victorious, to gain, to obtain, to acquire, to extract, to mine, to produce, to win over, to attract, to captivate" },
  { rank: 88, word: "schließen", meaning: "close, shut, conclude, finish, terminate, deduce, infer, establish, form, build, finalize, seal" },
  { rank: 89, word: "fühlen", meaning: "to feel, to sense, to touch, to sense by touch, to think, to believe, to be" },
  { rank: 90, word: "bieten", meaning: "offer, provide, present, feature, give, bid" },
  { rank: 91, word: "interessieren", meaning: "to interest, to be interested in, to attract, to appeal to" },
  { rank: 92, word: "erinnern", meaning: "remember, recall, remind, commemorate, observe" },
  { rank: 93, word: "ergeben", meaning: "to result in, to yield, to show, to produce, to surrender, to give up, devoted, loyal, faithful" },
  { rank: 94, word: "anbieten", meaning: "to offer, to provide, to propose, to suggest, to volunteer, to offer oneself, to make oneself available" },
  { rank: 95, word: "studieren", meaning: "to study, to major in, to examine, to investigate, to analyze, to memorize, to learn, to study (for a test)" },
  { rank: 96, word: "verbinden", meaning: "connect, join, link, unite, combine, put through, associate, relate, bandage, dress (a wound)" },
  { rank: 97, word: "ansehen", meaning: "look at, watch, view, regard, inspect, examine, check, review, consider, view as, see, notice, perceive" },
  { rank: 98, word: "fehlen", meaning: "be absent, be missing, lack, be short of, be insufficient, miss, fail to hit, be missed, make a mistake, err" },
  { rank: 99, word: "bedeuten", meaning: "mean, signify, represent, matter, be important, be relevant, explain, indicate, make clear" },
  { rank: 100, word: "vergleichen", meaning: "compare, contrast, liken, equate, settle, compromise, agree" },
  { rank: 101, word: "steigen", meaning: "ascend, go up, climb, increase, rise, grow, get in, board, enter, get out, alight, exit, participate, engage, get involved" },
  { rank: 102, word: "nutzen", meaning: "to use, to utilize, to benefit from, to take advantage of, benefit, use, utility, advantage" },
  { rank: 103, word: "schauen", meaning: "look, watch, see, look up, check, search, look at, gaze at, face" },
  { rank: 104, word: "verlassen", meaning: "leave, abandon, desert, forsake, rely on, count on, trust, deserted, abandoned, desolate, forsaken" },
  { rank: 105, word: "einsetzen", meaning: "to insert, to put in, to place, to use, to employ, to deploy, to utilize, to begin, to start, to set in, to commence, appoint, designate, install, assign" },
  { rank: 106, word: "ändern", meaning: "to change, to alter, to modify, to transform, to convert" },
  { rank: 107, word: "wachsen", meaning: "to grow, to increase, to wax, to develop, to mature, to grow up" },
  { rank: 108, word: "ausgehen", meaning: "go out, hang out, step out, run out, be depleted, be used up, be extinguished, turn off, assume, suppose, presume, originate from, derive from, stem from" },
  { rank: 109, word: "geschehen", meaning: "happened, occurred, taken place" },
  { rank: 110, word: "beschreiben", meaning: "describe, depict, explain, draw, trace" },
  { rank: 111, word: "annehmen", meaning: "to accept, to receive, to take, to assume, to suppose, to presume, to adopt, to take on, to assume (a role/stance)" },
  { rank: 112, word: "kriegen", meaning: "to get, to receive, to obtain, to manage, to achieve, to accomplish, to get done, get, receive, suffer, experience, catch, capture" },
  { rank: 113, word: "planen", meaning: "to plan, to arrange, to prepare, to design, to lay out, to draft, to anticipate, to foresee, to budget for" },
  { rank: 114, word: "wirken", meaning: "affect, influence, have an effect, impact, work, seem, appear, look, give the impression, be active, operate, function, weave, knit, manufacture, produce" },
  { rank: 115, word: "bezeichnen", meaning: "to name, to designate, to call, to refer to, to mark, to label, to tag, to describe, to characterize, to define" },
  { rank: 116, word: "befinden", meaning: "to be, to be located, to be situated, to judge, to evaluate, to deem, to find, to feel, to be (doing), to be in a state" },
  { rank: 117, word: "passieren", meaning: "happen, occur, take place, pass, cross, traverse, go through, strain, purée, sieve, filter" },
  { rank: 118, word: "rufen", meaning: "call, shout, phone, summon, invite, appoint, designate" },
  { rank: 119, word: "aufnehmen", meaning: "to receive, to accept, to take in, to record, to film, to shoot, to tape, to absorb, to take up, to incorporate, to begin, to start, to resume" },
  { rank: 120, word: "zunehmen", meaning: "to increase, to grow, to gain weight, to intensify, to grow stronger, to pick up, to gain importance, to grow in influence, to become more significant" },
  { rank: 121, word: "bestimmen", meaning: "determine, decide, establish, set, stipulate, identify, recognize, ascertain, influence, control, shape, govern" },
  { rank: 122, word: "fordern", meaning: "to demand, to request, to require, to claim, to challenge, to demand (a performance), to call for, challenge, demand effort from, stimulate, foster, promote, encourage" },
  { rank: 123, word: "gefallen", meaning: "to like, to please, to appeal to, to fall (in battle), to die (in combat), to perish" },
  { rank: 124, word: "öffnen", meaning: "to open, unclose, to start, to inaugurate, to launch, to make accessible, to make available, to unfold, to spread, to expand" },
  { rank: 125, word: "schlagen", meaning: "hit, strike, beat, punch, defeat, win against, flap, whip, chime, pitch, set up (a tent), make (camp), suggest, propose, recommend" },
  { rank: 126, word: "treten", meaning: "to step, to tread, to walk, to kick, to strike with foot, to enter, to join, to step into, come into effect, take effect, become effective, appear, perform, behave, act" },
  { rank: 127, word: "übernehmen", meaning: "take over, assume control, take charge, undertake, accept, assume, adopt, incorporate, implement, take responsibility for, cover, take on" },
  { rank: 128, word: "verändern", meaning: "change, alter, modify, adjust, transform, convert, reshape, remake, evolve, develop, shift" },
  { rank: 129, word: "lachen", meaning: "laugh, giggle, chuckle, mock, ridicule, laugh at, make fun of" },
  { rank: 130, word: "verwenden", meaning: "to use, to employ, to utilize, to apply, to implement" },
  { rank: 131, word: "wählen", meaning: "choose, select, vote, elect, dial" },
  { rank: 132, word: "erfolgen", meaning: "to occur, to take place, to happen, to ensue, to be carried out, to be performed, to be done, to be executed" },
  { rank: 133, word: "enthalten", meaning: "contain, include, hold, abstain, refrain, forbear, included, contained, comprised" },
  { rank: 134, word: "betrachten", meaning: "observe, examine, look at, consider, regard, view, reflect, ponder, meditate" },
  { rank: 135, word: "entscheiden", meaning: "decide, make a decision, resolve, determine, settle, choose, opt for, select" },
  { rank: 136, word: "gelingen", meaning: "to succeed, to manage, to turn out well" },
  { rank: 137, word: "kaufen", meaning: "buy, purchase, gain, win over, bribe, buy off, corrupt, to believe, to buy into, to fall for" },
  { rank: 138, word: "erfahren", meaning: "learn, find out, experience, discover, experienced, skilled, seasoned, hear, be informed, get to know" },
  { rank: 139, word: "vergessen", meaning: "to forget, to not recall, to neglect, to overlook, to disregard, to leave behind, to forget (an item)" },
  { rank: 140, word: "stattfinden", meaning: "to take place, to happen, to occur" },
  { rank: 141, word: "bewegen", meaning: "move, shift, touch, stir, get around" },
  { rank: 142, word: "feststellen", meaning: "to determine, to ascertain, to establish, to verify, to note, to fix, to secure, to fasten, to lock, to arrest, to detain, to apprehend" },
  { rank: 143, word: "verschwinden", meaning: "to disappear, to vanish, to be gone, to fade away, to diminish, to subside" },
  { rank: 144, word: "dienen", meaning: "to serve, to work, to be employed, to serve (a purpose), to be useful, to be for, to dedicate oneself, to devote oneself" },
  { rank: 145, word: "trinken", meaning: "to drink, drink heavily, binge drink, overdrink, drink (for animals), lap up, take (medicine), drink (medicine)" },
  { rank: 146, word: "auftreten", meaning: "to perform, to appear, to present oneself, to occur, to arise, to manifest, to behave, to act, to conduct oneself, to step on, to tread on" },
  { rank: 147, word: "stimmen", meaning: "to be correct, to be true, to be right, to agree, to tune, vote, cast a ballot, elect, agree, match, correspond, be correct" },
  { rank: 148, word: "verhalten", meaning: "behave, act, conduct oneself, relate, be proportional, stand in relation, restrained, subdued, moderate, cautious" },
  { rank: 149, word: "berichten", meaning: "report, inform, give an account, narrate, tell, recount, submit a report, present a report" },
  { rank: 150, word: "rechnen", meaning: "calculate, compute, reckon, count on, rely on, depend on, to calculate, to factor in, to take into account, to consider, to expect, to anticipate, to reckon with" }
];
